### ISSUE TITLE
Error logs coming for `http: superfluous response.WriteHeader call` when using otelhttp handler

### ISSUE THREAD

**Issue by vipul-rawat** [open-telemetry/opentelemetry-go-contrib#6053]
### Description

In the latest release the call to request.Write() is setting the response headers to `http.StatusOK` without checking if the WriteHeader is already called, this is causing issues when trying to set Status Codes and then trying to Write to the response.

### Environment

- OS: darwin
- Architecture: arm64
- Go Version: go 1.22
- `otelhttp` version: v0.54.0

### Steps To Reproduce

1. Using this code ...
```
package main

import (
	"fmt"

	"gofr.dev/pkg/gofr"
)

func main() {
	a := gofr.New()

	a.GET("/hello", HelloHandler)

	a.Run()
}

func HelloHandler(c *gofr.Context) (interface{}, error) {
	name := c.Param("name")
	if name == "" {
		c.Log("Name came empty")
		name = "World"
	}

	return fmt.Sprintf("Hello %s!", name), nil
}

```
2. Run ...
```
go run main.go

curl --location 'localhost:8000/hello'
```
3. See error ...
![image](https://github.com/user-attachments/assets/9c87bb09-4ab2-441d-8834-8b334299753d)

### Expected behavior

The Write() call should check if the wroteHeader is true before calling WriteHeader()

**Comment by dmathieu** [comment]
I'm unable to reproduce this running your sample example:

> WARN [12:04:43] Failed to load config from file: /.env, Err: open /.env: no such file or directory
INFO [12:04:43] Starting metrics server on port: 2121
INFO [12:04:43] Starting server on port: 8000
INFO [12:05:10] Name came empty
INFO [12:05:10] 28adde73d3a4db5359b386841c4099b5 200         345µs GET /hello

Also, based on stacktrace in the screenshot you're providing, it would appear the superfluous call to `WriteHeader` could be from gofr, not us?

**Comment by vipul-rawat** [comment]
I am able to reproduce with the following code - 
```
package main

import (
	"net/http"

	"github.com/gorilla/mux"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

func main() {
	r := mux.NewRouter()

	handler := http.HandlerFunc(func(wr http.ResponseWriter, r *http.Request) {
		wr.WriteHeader(http.StatusCreated)

		_, _ = wr.Write([]byte("Hello World!"))
	})

	// defining a new otelhttp handler
	h := otelhttp.NewHandler(handler, "gofr-router")

	// register a hello route
	r.NewRoute().Methods(http.MethodGet).Path("/hello").Handler(h)

	err := http.ListenAndServe("localhost:8000", r)
	if err != nil {
		panic(err)
	}
}
```

Output:

> 2024/08/27 16:33:12 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:78)

**Comment by dmathieu** [comment]
I still don't reproduce with that code.

Moreover, the mentioned method does check whether the header was written before or not, and skips if it was.
So it's likely another middleware is writing outside of otelhttp.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go#L73-L79

**Comment by mehdy** [comment]
This if block has been removed in this PR: https://github.com/open-telemetry/opentelemetry-go-contrib/commit/c6199195bc1fd936dd33e25ee3fff8d3f8194327#diff-cd9dbf33a4742e5cca53d128ebad2d1e61fdc1b41d4978db6d2a3d6a39c4a522L67-L69

**Comment by lambrospetrou** [comment]
Hitting this as well https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5438#issuecomment-2316313313

**Comment by ash2k** [comment]
Hitting this too. All those methods that call the real `WriteHeader()` probably don't need to. They should only check if `w.statusCode` has been set already, and if not, set it to `200` (without calling the real `WriteHeader()`). This is simpler and doesn't have any chances of triggering some unexpected behavior in the wrapped response writer. It may too be some sort of wrapper.

**Comment by RangelReale** [comment]
I'm getting this same error on otelmux (contrib v0.54.0).

```
2024/09/02 12:45:02 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.getRRW.func2.1 (mux.go:104)
```

```
go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux v0.54.0
```

**Comment by dmathieu** [comment]
This has been fixed in main, and will be available with the next release.

**Comment by dicki** [comment]
@dmathieu 
Still seeing this with `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.63.0`

`http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:83)`

**Comment by dmathieu** [comment]
Could you open a new issue with a small reproduction case?
